# NumPy Arrays

### NumPy Basics 

In [ ]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_list = [[1,2,3],[2,3,4],[3,4,5]]

In [6]:
np.array(my_list)

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.zeros(1)

array([0.])

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### np.ones(x) produces an array with x number of ones

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

### linpace(x,y,z) produces an array of z equally spaced number in the range x to y

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### np.eye(n) makes an identity matrix of n x n 

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.random.rand(x) generates an array of x random numbers uniformly distributed from 0 to 1

In [26]:
np.random.rand(5)

array([0.6817552 , 0.05659997, 0.20502483, 0.12833775, 0.48420846])

### np.random.rand(x,y) generates an 2-D array with x rows and y columns of  random numbers uniformly distributed from 0 to 1### 

In [27]:
np.random.rand(5,5)

array([[0.98530689, 0.7587202 , 0.93499179, 0.33957809, 0.55249432],
       [0.35370626, 0.50898283, 0.10590454, 0.52682157, 0.50656962],
       [0.60200372, 0.17023419, 0.47249397, 0.35482226, 0.35291593],
       [0.51455034, 0.68364655, 0.76089116, 0.91819022, 0.61124417],
       [0.85609624, 0.99423557, 0.67757853, 0.19632796, 0.20431528]])

### np.random.randn(x,y) generates an 2-D array with x rows and y columns of  random numbers distributed using standard normal distribution from 0 to 1### 

In [28]:
np.random.randn(2)

array([0.03463739, 0.69489182])

In [29]:
np.random.randint(1,100,10)

array([58, 62, 56, 50,  5,  7, 72,  4, 91, 26])

In [31]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([24, 18, 12, 44, 11, 32, 12, 36,  6, 17])

In [34]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

44

In [37]:
ranarr.min()

6

In [38]:
ranarr

array([24, 18, 12, 44, 11, 32, 12, 36,  6, 17])

In [39]:
ranarr.argmax()

3

In [40]:
ranarr.argmin()

8

In [41]:
arr.shape

(25,)

In [42]:
arr = arr.reshape(5,5)

In [43]:
arr.shape

(5, 5)

In [44]:
arr.dtype

dtype('int64')

In [45]:
from numpy.random import randint

In [46]:
randint(2,10)

2